//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medico_Forms.MedicosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MedicosService.SegipServiceSoap")]
    public interface SegipServiceSoap {
        
        // CODEGEN: Generating message contract since element name CI from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarCI", ReplyAction="*")]
        Medico_Forms.MedicosService.VerificarCIResponse VerificarCI(Medico_Forms.MedicosService.VerificarCIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarCI", ReplyAction="*")]
        System.Threading.Tasks.Task<Medico_Forms.MedicosService.VerificarCIResponse> VerificarCIAsync(Medico_Forms.MedicosService.VerificarCIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarCIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarCI", Namespace="http://tempuri.org/", Order=0)]
        public Medico_Forms.MedicosService.VerificarCIRequestBody Body;
        
        public VerificarCIRequest() {
        }
        
        public VerificarCIRequest(Medico_Forms.MedicosService.VerificarCIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarCIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public VerificarCIRequestBody() {
        }
        
        public VerificarCIRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarCIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarCIResponse", Namespace="http://tempuri.org/", Order=0)]
        public Medico_Forms.MedicosService.VerificarCIResponseBody Body;
        
        public VerificarCIResponse() {
        }
        
        public VerificarCIResponse(Medico_Forms.MedicosService.VerificarCIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarCIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarCIResult;
        
        public VerificarCIResponseBody() {
        }
        
        public VerificarCIResponseBody(bool VerificarCIResult) {
            this.VerificarCIResult = VerificarCIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SegipServiceSoapChannel : Medico_Forms.MedicosService.SegipServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SegipServiceSoapClient : System.ServiceModel.ClientBase<Medico_Forms.MedicosService.SegipServiceSoap>, Medico_Forms.MedicosService.SegipServiceSoap {
        
        public SegipServiceSoapClient() {
        }
        
        public SegipServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SegipServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SegipServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SegipServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Medico_Forms.MedicosService.VerificarCIResponse Medico_Forms.MedicosService.SegipServiceSoap.VerificarCI(Medico_Forms.MedicosService.VerificarCIRequest request) {
            return base.Channel.VerificarCI(request);
        }
        
        public bool VerificarCI(string CI) {
            Medico_Forms.MedicosService.VerificarCIRequest inValue = new Medico_Forms.MedicosService.VerificarCIRequest();
            inValue.Body = new Medico_Forms.MedicosService.VerificarCIRequestBody();
            inValue.Body.CI = CI;
            Medico_Forms.MedicosService.VerificarCIResponse retVal = ((Medico_Forms.MedicosService.SegipServiceSoap)(this)).VerificarCI(inValue);
            return retVal.Body.VerificarCIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Medico_Forms.MedicosService.VerificarCIResponse> Medico_Forms.MedicosService.SegipServiceSoap.VerificarCIAsync(Medico_Forms.MedicosService.VerificarCIRequest request) {
            return base.Channel.VerificarCIAsync(request);
        }
        
        public System.Threading.Tasks.Task<Medico_Forms.MedicosService.VerificarCIResponse> VerificarCIAsync(string CI) {
            Medico_Forms.MedicosService.VerificarCIRequest inValue = new Medico_Forms.MedicosService.VerificarCIRequest();
            inValue.Body = new Medico_Forms.MedicosService.VerificarCIRequestBody();
            inValue.Body.CI = CI;
            return ((Medico_Forms.MedicosService.SegipServiceSoap)(this)).VerificarCIAsync(inValue);
        }
    }
}
